/* ~~~~~~ Questão 1 - Inadimplentes ~~~~~~ */ 

SELECT P.NOME, DAY(PG.DT_PAGAMENTO) AS 'DIA_MES', C.VALOR_PARCELA
FROM PESSOAS AS P
INNER JOIN PAGAMENTOS AS PG
ON P.ID = PESSOA_ID
INNER JOIN CONTRATOS AS C
ON P.CONTRATO_ID = C.ID
WHERE P.INADIMPLENTES = 'S';

/* ~~~~~~ Questão 2 - Pagamento Completo ~~~~~~ */ 

SELECT P.NOME, C.VALOR_PARCELA * C.PARCELAS AS 'VALOR_TOTAL'
FROM PESSOAS AS P
INNER JOIN CONTRATOS AS C
ON P.CONTRATO_ID = C.ID
WHERE P.INADIMPLENTES = 'N';